#%RAML 1.0
title: StarWarsCSVQry
description: Request to https://swapi.dev/ Star Wars API

/all:
  get:
    description: Get all characters
    responses:
      200:
        body: 
          application/json:
            example: !include people.json
/gender: 
  get:
    description: List the character gender
    queryParameters:
      gender: 
        description: Gender type. [male, female, n/a]
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            example: !include people.json